Working on this has taken a lot of my time and I have been purchasing games for testing. 
If you wish to support, please consider donating to my ko_fi account. 
Maybe if we get enough donations I can buy a G923 for testing!

ko_fi: mhytee
