Working on this has taken up A LOT of my time. If you wish to support, please consider sponsoring me or donating to my ko_fi account. 

Your support enables me to continue buying games to test with, improving our Trueforce-compatible effects synthesis engine, improving our documentation, and assisting users. 

ko_fi: https://ko-fi.com/mhytee
GitHub Sponsorship: https://github.com/sponsors/Mhytee
